### ISSUE TITLE
對齊討論

### ISSUE THREAD

**Issue by cody0704** [Zhouchaowen/xdp_labs#1]
https://github.com/Zhouchaowen/xdp_labs/blob/f616a1244f5e3291619660ea91ed1b92dd18025f/parse_udp_dns/main.go#L83

您好，我一直想有人可以討論 XDP 相關技術上的研發，看到你對於對齊的問題
我在另一邊有提出一些方案，你可以參考一下，這邊有人採納了我的解決方案

在 C 中讓結構以 `pack(push, 1)` 中對結構進行對齊為 1 字節，這樣就可以跟 Go 程式正常解析相同的結構的長度，就不用額外做對齊
https://github.com/zhao-kun/xdp-redirect/pull/1

**Comment by Zhouchaowen** [comment]
@cody0704 我也是才学XDP不久, 非常感谢你指出这个问题, 我尝试了一下, 的确可以。

**Comment by cody0704** [comment]
@Zhouchaowen 
有機會多討論，我看到你有很多不錯的實驗項目
我也有進行類似的東西
https://github.com/cody0704/xdp-examples

或許可以一起整理一下，弄一些有趣的東西

這邊就關閉了
